#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=pvd_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:15:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
source activate pvd4

# Run your code
python -u pvd_test.py --dataroot /data --batch_size 1 --model path_to_model --category bagel --workers 0 --anomaly