#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=full_pipeline
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:25:00
#SBATCH --mem=64000M
#SBATCH --output=slurm_output_%A.out

module purge
source activate pvd4

# Run your code
python -u test_generation_original.py --category bagel --dataroot data --model model/epoch_2299_10k_normalized.pth