#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=pvd_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:26:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
source activate pvd
export CUDA_HOME=$CONDA_PREFIX

# Run your code
python -u PVD/pvd_test.py --dataroot /home/lcur0949/PVD/data --anomaly_time 20 --batch_size 1 --model /home/lcur0949/Computer-vision-2-project/checkpoints/epoch_2499_10k_normalize_true.pth --workers 0 --anomaly --eval_gen --test_folder /home/lcur0949/PVD/data/bagel/test