#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=train_bagel_generation
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=48:00:00
#SBATCH --mem=32000M
#SBATCH --output=bagel_generation_train_%A.out

module purge
module load 2022
#module load Anaconda3/2022.05

source activate pvd

cd $HOME/repo/PVD

srun python train_generation.py --dataroot $HOME/data/mvtec --category bagel --bs 32 --niter 3