#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=Stage1-SDF
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=08:00:00
#SBATCH --mem=32000M
#SBATCH --output=stage_1_diffusion_sdf_%A.out

module load 2021
module load Anaconda3/2021.05

# activate the environment
source activate diffusionsdf

srun python -u train.py -e config/stage1_sdf/ -b 32 -w 8 # -b for batch size, -w for workers, -r to resume training